from PyQt5 import QtCore, QtGui, QtWidgets

class Design_app(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 650, 480))
        self.tabWidget.setObjectName("tabWidget")
        self.dowload_video = QtWidgets.QWidget()
        self.dowload_video.setObjectName("dowload_video")
        self.main_dowload_frame = QtWidgets.QFrame(self.dowload_video)
        self.main_dowload_frame.setGeometry(QtCore.QRect(0, 0, 650, 450))
        self.main_dowload_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_dowload_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_dowload_frame.setObjectName("main_dowload_frame")
        self.title_frame = QtWidgets.QFrame(self.main_dowload_frame)
        self.title_frame.setGeometry(QtCore.QRect(10, 10, 640, 30))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")

        self.input_video_frame = QtWidgets.QFrame(self.main_dowload_frame)
        self.input_video_frame.setGeometry(QtCore.QRect(10, 50, 630, 50))
        self.input_video_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_video_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_video_frame.setObjectName("input_video_frame")
        self.link_edit = QtWidgets.QLineEdit(self.input_video_frame)
        self.link_edit.setGeometry(QtCore.QRect(170, 10, 341, 31))
        self.link_edit.setObjectName("link_edit")
        self.check_btn = QtWidgets.QPushButton(self.input_video_frame)
        self.check_btn.setGeometry(QtCore.QRect(520, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calisto MT")
        font.setPointSize(10)
        self.check_btn.setFont(font)
        self.check_btn.setObjectName("check_btn")

        self.description_video = QtWidgets.QFrame(self.main_dowload_frame)
        self.description_video.setGeometry(QtCore.QRect(10, 110, 631, 191))
        self.description_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.description_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.description_video.setObjectName("description_video")

        self.description_video_lab = QtWidgets.QLabel(self.description_video)
        self.description_video_lab.setGeometry(QtCore.QRect(330, 40, 271, 151))
        font = QtGui.QFont()
        self.description_video_lab.setFont(font)
        self.description_video_lab.setWordWrap(True)
        self.description_video_lab.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.description_video_lab.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.description_video_lab.setObjectName("description_video_lab")


        self.folder_save = QtWidgets.QFrame(self.main_dowload_frame)
        self.folder_save.setGeometry(QtCore.QRect(10, 310, 621, 51))
        self.folder_save.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.folder_save.setFrameShadow(QtWidgets.QFrame.Raised)
        self.folder_save.setObjectName("folder_save")
        self.fold_video_line_edit = QtWidgets.QLineEdit(self.folder_save)
        self.fold_video_line_edit.setGeometry(QtCore.QRect(190, 10, 341, 31))
        self.fold_video_line_edit.setObjectName("fold_video_line_edit")

        self.dowload_frame = QtWidgets.QFrame(self.main_dowload_frame)
        self.dowload_frame.setGeometry(QtCore.QRect(10, 360, 621, 91))
        self.dowload_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dowload_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dowload_frame.setObjectName("dowload_frame")

        self.review_btn = QtWidgets.QPushButton(self.folder_save)
        self.review_btn.setGeometry(QtCore.QRect(540, 10, 75, 31))
        self.review_btn.setFont(font)
        self.review_btn.setObjectName("review_btn")

        self.dowload_ProgBar = QtWidgets.QProgressBar(self.dowload_frame)
        self.dowload_ProgBar.setGeometry(QtCore.QRect(10, 40, 611, 31))
        self.dowload_ProgBar.setFont(font)
        self.dowload_ProgBar.setProperty("value", 0)
        self.dowload_ProgBar.setObjectName("dowload_ProgBar")

        self.dowload_btn = QtWidgets.QPushButton(self.dowload_frame)
        self.dowload_btn.setGeometry(QtCore.QRect(500, 0, 111, 31))
        self.dowload_btn.setFont(font)
        self.dowload_btn.setObjectName("dowload_btn")

        self.link_video_lab = QtWidgets.QLabel(self.input_video_frame)
        self.link_video_lab.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.link_video_lab.setFont(font)
        self.link_video_lab.setObjectName("link_video_lab")

        self.fold_video_lab = QtWidgets.QLabel(self.folder_save)
        self.fold_video_lab.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.fold_video_lab.setFont(font)
        self.fold_video_lab.setObjectName("fold_video_lab")

        self.title_video_lab = QtWidgets.QLabel(self.description_video)
        self.title_video_lab.setGeometry(QtCore.QRect(10, -20, 620, 60))
        font.setPointSize(12)
        self.title_video_lab.setFont(font)
        self.title_video_lab.setObjectName("title_video_lab")

        self.name_video_edit = QtWidgets.QLineEdit(self.description_video)
        self.name_video_edit.setGeometry(QtCore.QRect(160,0,400,25))
        self.name_video_edit.setFont(font)
        self.name_video_edit.setObjectName("name_video")

        self.title_lab = QtWidgets.QLabel(self.title_frame)
        self.title_lab.setGeometry(QtCore.QRect(120, 0, 390, 20))
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")

        self.img_lab = QtWidgets.QLabel(self.description_video)
        self.img_lab.setGeometry(QtCore.QRect(10, 40, 301, 151))
        self.img_lab.setFont(font)
        self.img_lab.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.img_lab.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.img_lab.setObjectName("img_lab")

        self.description_video = QtWidgets.QFrame(self.main_dowload_frame)
        self.description_video.setGeometry(QtCore.QRect(10, 110, 631, 191))
        self.description_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.description_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.description_video.setObjectName("description_video")


        self.tabWidget.addTab(self.dowload_video, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_lab.setText(_translate("MainWindow", "Скачать видео с ютуб бесплатно и без регистрации!"))
        self.check_btn.setText(_translate("MainWindow", "Проверить"))
        self.link_video_lab.setText(_translate("MainWindow", "Укажите ссылку на видео"))
        self.title_video_lab.setText(_translate("MainWindow", "Название видео"))
        self.description_video_lab.setText(_translate("MainWindow", "Описание видео"))
        self.img_lab.setText(_translate("MainWindow", "Картинка видео"))
        self.review_btn.setText(_translate("MainWindow", "Обзор"))
        self.fold_video_lab.setText(_translate("MainWindow", "Выбирете место сохранения:"))
        self.dowload_btn.setText(_translate("MainWindow", "Скачать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dowload_video), _translate("MainWindow", "Скачать видео"))

